nsg_name = "mynsg_test_sfc"
region_name = "centralus"
rg_name = "CIC_PH_Azure_Capability_Build"
vnet_name = "myvnet_test"
vnet_CIDR = [ "10.50.0.0/16" ]
dns_server = [ "value" ]
primary_subnet_CIDR = "10.50.1.0/24"
primary_subnet_name = "subnet1_test"
secondary_subnet_CIDR = "10.50.1.0/24"
secondary_subnet_name = "subnet2_test"
environment_name = "sfctest_env"